[pytest]
testpaths =
    simulation-vinesh-philip-chandan/vinesh
    simulation-vinesh-philip-chandan/philip-chandan/cohort/tests
    simulation-vinesh-philip-chandan/philip-chandan/tests
pythonpath =
    simulation-vinesh-philip-chandan
    simulation-vinesh-philip-chandan/vinesh
    simulation-vinesh-philip-chandan/philip-chandan
    visualization-jasim
